backend:
  name: git-gateway
  branch: main

media_folder: "imagens"
public_folder: "/imagens"

collections:
  - name: "posts"
    label: "Posts do Blog"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - label: "Categoria"
        name: "categoria"
        widget: "select"
        options:
          - "Estratégia"
          - "Conteúdo"
          - "Anúncios"
          - "Marca Pessoal"
          - "Métricas"
      - { label: "Resumo", name: "resumo", widget: "text" }
      - { label: "Imagem de capa", name: "capa", widget: "image", required: false }
      - { label: "Conteúdo", name: "body", widget: "markdown" }
      - { label: "Publicado?", name: "publicado", widget: "boolean", default: true }
